### ISSUE TITLE
nullpointer after compiling stubs

### ISSUE THREAD

**Issue by renstoonen** [chenjianjx/wsdl2html#10]
I get a nullpointer after compiling the stubs so it does not generate the HTML when i execute the bat file in cmd. 
I've tried my own WSDL and the WSDL that is used as an example on wsdl2html.com, both give the same error. Am i doing something wrong?
![image](https://cloud.githubusercontent.com/assets/8721805/21844133/ccbf53a4-d7ed-11e6-8ed9-5c7ee7e071c4.png)

**Comment by chenjianjx** [comment]
Did you use version 3.0.2 with maven? Or run it another way?

**Comment by renstoonen** [comment]
I ran it from the command line with jdk 1.8 in my PATH variable.

**Comment by chenjianjx** [comment]
1. Do you run it according to https://github.com/chenjianjx/wsdl2html#run-as-a-command-line-tool ?
2. It seems ````JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();```` return null on your computer.  Can you let me know the exact version of your JDK ?  And make sure you used JDK instead of just JRE

**Comment by renstoonen** [comment]
Sorry for the late reaction, i ran it according to the link yes. I've tried the tool at home with the paypal wsdl but it gives the exactly same error. The JDK version I use is JDK1.8.0_111. I checked and i am using the JDK for sure

**Comment by chenjianjx** [comment]
According to this stackoverflow page, it seems you don't have tools.jar on your classpath. 

http://stackoverflow.com/questions/15513330/toolprovider-getsystemjavacompiler-returns-null-usable-with-only-jre-install
