### ISSUE TITLE
WDSL documentation

### ISSUE THREAD

**Issue by mccalv** [chenjianjx/wsdl2html#11]
Hello, I am trying to understand and adapt your tool, but I don't see the wsdl:documentation reported in the generated HTML. 
Is it something in development? 
Regards

**Comment by chenjianjx** [comment]
Can you give me a sample WSDL you want to try with?

**Comment by chenjianjx** [comment]
They will not be shown due to JDK's "wsimport" limit, although there could be other ways to make it happen. See https://github.com/chenjianjx/wsdl2html/issues/13

**Comment by igand** [comment]
I see. Thanks for fast reply.
