### ISSUE TITLE
Generated Temp Files

### ISSUE THREAD

**Issue by robrushton** [chenjianjx/wsdl2html#12]
It seems during the process of creating the html, a bunch of extra files are created. After the html is made, these files are no longer needed. Wouldn't it be beneficial to delete the temp files after the document is created?

**Comment by chenjianjx** [comment]
What you said makes sense.  However, we still need them if we want to find out what's going on behind the scene, by checking the generated Java files, especially when you see a problem. 

So, I think we should put them under OS's temp directory.  

Pull requests are well come.

**Comment by robrushton** [comment]
The burden of cleaning up should fall on the creator. I can only speak for Windows, but the OS temp file is never automatically cleaned. So if this is run on anything automated, trash will just build up until a disk cleanup-type action is performed or until it is manually deleted. Another possible solution would be to add a debug feature so output was only saved if debug is turned on. 

If that sounds like a good change, I will work on it when I get time and send a pull request. If not, I will just implement it on my end.

**Comment by chenjianjx** [comment]
I think you are right.  Please add a dedicated debug parameter (--retain-files e.g.) to make it happen.  And also update the readme file please.
