### ISSUE TITLE
Fails - Requires .metro/auth or -Xauthfile

### ISSUE THREAD

**Issue by vikasbo** [chenjianjx/wsdl2html#19]
When providing the wsdl url in the below format:

`http[s]://user:password@host:port//<url-path>`

The error message is:

> Exception in thread "main" org.jaxws.wsdl2bytecodes.service.WsdlImportException: 
[INFO] parsing WSDL...
[INFO] 
[INFO] 
[INFO] [ERROR] Server returned HTTP response code: 401 for URL: http://admin:pass;word@localhost:8080/services/app?wsdl,  "http://admin:pass;word@localhost:8080/services/app?wsdl" needs authorization, please provide authorization file with read access at /home/user/.metro/auth or use -Xauthfile to give the authorization file and on each line provide authorization information using this format : http[s]://user:password@host:port//<url-path>
[INFO] 
[INFO] 
[ERROR] Exception in thread "main" com.sun.tools.internal.ws.wscompile.AbortException
[ERROR] 	at com.sun.tools.internal.ws.wsdl.parser.MetadataFinder$WSEntityResolver.resolveEntity(MetadataFinder.java:187)
[ERROR] 	at com.sun.tools.internal.ws.wsdl.parser.DOMForest.parse(DOMForest.java:198)
[ERROR] 	at com.sun.tools.internal.ws.wsdl.parser.DOMForest.parse(DOMForest.java:134)
[ERROR] 	at com.sun.tools.internal.ws.wsdl.parser.MetadataFinder.parseWSDL(MetadataFinder.java:96)
[ERROR] 	at com.sun.tools.internal.ws.wscompile.WsimportTool.buildWsdlModel(WsimportTool.java:424)
[ERROR] 	at com.sun.tools.internal.ws.wscompile.WsimportTool.run(WsimportTool.java:190)
[ERROR] 	at com.sun.tools.internal.ws.wscompile.WsimportTool.run(WsimportTool.java:168)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at com.sun.tools.internal.ws.Invoker.invoke(Invoker.java:159)
[ERROR] 	at com.sun.tools.internal.ws.WsImport.main(WsImport.java:42)

	at org.jaxws.wsdl2bytecodes.service.Wsdl2ByteCodes.doWsImport(Wsdl2ByteCodes.java:150)

**Comment by chenjianjx** [comment]
I think you can do what the stacktrace told you.  Put some auth file on your machine. 
wsdl2html calls wsimport to parse wsdl.  It doesn't do anything extra.
