### ISSUE TITLE
How am I supposed to execute the .jar?

### ISSUE THREAD

**Issue by martinfou** [chenjianjx/wsdl2html#2]
I have tried the following

C:\Users\marfourn\Downloads>java -jar wsdl2html-1.0.3.jar ClientClaimsHistoryService.wsdl

and I got

aucun attribut manifest principal dans wsdl2html-1.0.3.jar

**Comment by chenjianjx** [comment]
can you translate what you have got into English?

**Comment by dmltommywong** [comment]
no main manifest attribute, in wsdl2html-1.0.3.jar

that's what we are getting

**Comment by boredland** [comment]
Same problem here. How is it supposed to be run?

**Comment by chenjianjx** [comment]
Sorry for the late reply.  I will address this issue in a day.

**Comment by chenjianjx** [comment]
Sorry for the late fix.   I've turned the project into a maven project.  You can check out project home page or do a quick one as follows:  

## Run as a command line tool

```shell

mvn package 
cd target 
unzip target/wsdl2html-some-version-jarset.zip -d /path/to/your/dir

# Go to the direction of extraction and you will see an executable file. Run it like, 

./wsdl2html.sh http://.../some?wsdl /path/to/your/html/directory  # or wsdl2html.bat for windows

```

**Comment by chenjianjx** [comment]
Can you guys let me know whether it works after trying it?
