### ISSUE TITLE
I can't compile the project with openjdk 11.0.4

### ISSUE THREAD

**Issue by aseques** [chenjianjx/wsdl2html#24]
I intend to work with wsdl2html as a command line tool, when I tried to compile through maven I get some errors (see below)
I am not very fluent in java, so I'm a bit lost, but it seems that the issues come because javax.jws is no longer part of the core for java 11, (and should be explicitly declared), I found this solution [here](https://stackoverflow.com/questions/54516361/how-to-use-webservices-on-java-11-package-javax-jws-does-not-exist), but I don't know how to do the integration

> $ mvn package
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.github.chenjianjx:wsdl2html:jar:4.0.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 85, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 58, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 71, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------< com.github.chenjianjx:wsdl2html >-------------------
[INFO] Building SOAP WSDL to Html 4.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ wsdl2html ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ wsdl2html ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 29 source files to /tmp/wsdl2html/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[11,17] package javax.jws does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[12,17] package javax.jws does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[13,33] package javax.xml.bind.annotation does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[48,60] cannot find symbol
  symbol:   class XmlElement
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[96,109] cannot find symbol
  symbol:   class WebParam
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[107,24] cannot find symbol
  symbol:   class WebParam
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[116,43] cannot find symbol
  symbol:   class XmlElement
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/WebServiceStubSetFactory.java:[9,17] package javax.jws does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/wsdl2html/service/Wsdl2Html.java:[5,17] package javax.jws does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[11,33] package javax.xml.bind.annotation does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[12,33] package javax.xml.bind.annotation does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[31,17] cannot find symbol
  symbol:   class XmlElement
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[31,61] cannot find symbol
  symbol:   class XmlElement
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[64,25] cannot find symbol
  symbol:   class WebParam
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[67,146] cannot find symbol
  symbol:   class WebParam
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[81,17] cannot find symbol
  symbol:   class WebResult
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[81,70] cannot find symbol
  symbol:   class WebResult
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[83,122] cannot find symbol
  symbol:   class WebResult
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[109,51] cannot find symbol
  symbol:   class WebParam
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[110,41] cannot find symbol
  symbol:   class WebParam
  location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/WebServiceStubSetFactory.java:[33,56] cannot find symbol
  symbol:   class WebMethod
  location: class org.jaxws.stub2html.service.WebServiceStubSetFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/wsdl2html/service/Wsdl2Html.java:[49,78] cannot find symbol
  symbol:   class WebService
  location: class org.jaxws.wsdl2html.service.Wsdl2Html
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[36,60] cannot find symbol
  symbol:   class XmlType
  location: class org.jaxws.stub2html.service.Variable2Stub
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[79,55] cannot find symbol
  symbol:   class XmlType
  location: class org.jaxws.stub2html.service.Variable2Stub
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[90,51] cannot find symbol
  symbol:   class XmlSeeAlso
  location: class org.jaxws.stub2html.service.Variable2Stub
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[120,64] cannot find symbol
  symbol:   class XmlSeeAlso
  location: class org.jaxws.stub2html.service.Variable2Stub
[INFO] 26 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.468 s
[INFO] Finished at: 2019-11-07T09:59:28+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project wsdl2html: Compilation failure: Compilation failure: 
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[11,17] package javax.jws does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[12,17] package javax.jws does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[13,33] package javax.xml.bind.annotation does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[48,60] cannot find symbol
[ERROR]   symbol:   class XmlElement
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[96,109] cannot find symbol
[ERROR]   symbol:   class WebParam
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[107,24] cannot find symbol
[ERROR]   symbol:   class WebParam
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[116,43] cannot find symbol
[ERROR]   symbol:   class XmlElement
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/WebServiceStubSetFactory.java:[9,17] package javax.jws does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/wsdl2html/service/Wsdl2Html.java:[5,17] package javax.jws does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[11,33] package javax.xml.bind.annotation does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[12,33] package javax.xml.bind.annotation does not exist
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[31,17] cannot find symbol
[ERROR]   symbol:   class XmlElement
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[31,61] cannot find symbol
[ERROR]   symbol:   class XmlElement
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[64,25] cannot find symbol
[ERROR]   symbol:   class WebParam
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[67,146] cannot find symbol
[ERROR]   symbol:   class WebParam
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[81,17] cannot find symbol
[ERROR]   symbol:   class WebResult
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[81,70] cannot find symbol
[ERROR]   symbol:   class WebResult
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[83,122] cannot find symbol
[ERROR]   symbol:   class WebResult
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[109,51] cannot find symbol
[ERROR]   symbol:   class WebParam
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/JavaLanguageVariableFactory.java:[110,41] cannot find symbol
[ERROR]   symbol:   class WebParam
[ERROR]   location: class org.jaxws.stub2html.service.JavaLanguageVariableFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/WebServiceStubSetFactory.java:[33,56] cannot find symbol
[ERROR]   symbol:   class WebMethod
[ERROR]   location: class org.jaxws.stub2html.service.WebServiceStubSetFactory
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/wsdl2html/service/Wsdl2Html.java:[49,78] cannot find symbol
[ERROR]   symbol:   class WebService
[ERROR]   location: class org.jaxws.wsdl2html.service.Wsdl2Html
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[36,60] cannot find symbol
[ERROR]   symbol:   class XmlType
[ERROR]   location: class org.jaxws.stub2html.service.Variable2Stub
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[79,55] cannot find symbol
[ERROR]   symbol:   class XmlType
[ERROR]   location: class org.jaxws.stub2html.service.Variable2Stub
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[90,51] cannot find symbol
[ERROR]   symbol:   class XmlSeeAlso
[ERROR]   location: class org.jaxws.stub2html.service.Variable2Stub
[ERROR] /tmp/wsdl2html/src/main/java/org/jaxws/stub2html/service/Variable2Stub.java:[120,64] cannot find symbol
[ERROR]   symbol:   class XmlSeeAlso
[ERROR]   location: class org.jaxws.stub2html.service.Variable2Stub
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by chenjianjx** [comment]
Fixed in version 4.1.0
