### ISSUE TITLE
Docker on Windows and Powershell

### ISSUE THREAD

**Issue by rvencu** [chenjianjx/wsdl2html#29]
Hi, I try to use this command but I get this error

docker run --rm -v ${pwd}/output:/usr/src/output wsdl2html http://www.webservicex.com/globalweather.asmx?wsdl

Unhandled exception: Drive has not been shared

How to share the drive?

**Comment by rvencu** [comment]
got it, nevermind

**Comment by rvencu** [comment]
It is still frustrating. I was able to succesfully run this command

docker run --rm -v ${pwd}/output://rchead/temp wsdl2html http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL

and I get this feedback

Please find the HTML files at /usr/src/output/15864452594617408864194235564688/html

There is nothing in the shared drive though....

**Comment by rvencu** [comment]
Got it. Proper command is

docker run --rm -v c:/temp:/usr/src/output wsdl2html http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL

**Comment by chenjianjx** [comment]
Thank you for the report.  I updated the readme.md to avoid similar confusion in the future. 

docker run --rm \
  -v **/path/to/your/html/directory**:/usr/src/output \
  wsdl2html http://.../some?wsdl
