### ISSUE TITLE
Create git tags for newer releases

### ISSUE THREAD

**Issue by stadler** [chenjianjx/wsdl2html#32]
The [the documentation](https://github.com/chenjianjx/wsdl2html) on how to run this app is ok, but there is one thing missing:
How do i get the code that is to be run. My naive approach was to download the latest release (3.0.2) and run the stuff. 
<img width="207" alt="Bildschirmfoto 2020-07-07 um 22 32 45" src="https://user-images.githubusercontent.com/974833/86839627-f58abf80-c0a1-11ea-9767-315c4670af96.png">

Unfortunatelly the actual latest release was 4.0.1, but as there no git tags for the newer releases this was not clear. This caused the issue #31 .

Therefore I would recommend to either:
* Tag all the newer releases since 3.0.2 or
* Improve the documentation to say, that one should git clone the repo to get the code and not use the releases.

**Comment by chenjianjx** [comment]
Yes, you are right.  I'll fix it soon

**Comment by chenjianjx** [comment]
I've deleted all the releases/tags and let users know in Readme.md that they have to clone or download the code.

Thank you for reporting the problem.
