### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by EddyVos** [chenjianjx/wsdl2html#4]
Hi There,

I love your project!!! Great tool to document WSDL files.
But could you please help me with an error that I get while documenting a large WSDL file?
Looks like the GenericUtils class produces an error when I try to use the tool:

> Java files generated at: D:\Downloads\wsdl2html-2.0.1-jarset\wsdl2html-2.0.1\.\test\stubs-14652014259001909405815451145366\20160606102345971\VOGxyqaHEj
> Exception in thread "main" java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class
>         at org.jaxws.stub2html.util.GenericsUtils.digFromGenericType(GenericsUtils.java:46)
>         at org.jaxws.stub2html.util.GenericsUtils.digFromGenericType(GenericsUtils.java:44)
>         at org.jaxws.stub2html.util.GenericsUtils.chooseOneType(GenericsUtils.java:35)
>         at org.jaxws.stub2html.util.GenericsUtils.getFieldGenericType(GenericsUtils.java:19)
>         at org.jaxws.stub2html.service.JavaLanguageVariableFactory.createVariableFromField(JavaLanguageVariableFactory.java:41)
>         at org.jaxws.stub2html.service.Variable2Stub.convertFieldsToChildStubs(Variable2Stub.java:44)
>         at org.jaxws.stub2html.service.Variable2Stub.convertToStub(Variable2Stub.java:35)
>         at org.jaxws.stub2html.service.Variable2Stub.convertFieldsToChildStubs(Variable2Stub.java:44)
>         at org.jaxws.stub2html.service.Variable2Stub.convertToStub(Variable2Stub.java:35)
>         at org.jaxws.stub2html.service.Variable2Stub.convertFieldsToChildStubs(Variable2Stub.java:44)
>         at org.jaxws.stub2html.service.Variable2Stub.convertToStub(Variable2Stub.java:35)
>         at org.jaxws.stub2html.service.Variable2Stub.convertFieldsToChildStubs(Variable2Stub.java:44)
>         at org.jaxws.stub2html.service.Variable2Stub.convertToStub(Variable2Stub.java:35)
>         at org.jaxws.stub2html.service.Variable2Stub.convertFieldsToChildStubs(Variable2Stub.java:44)
>         at org.jaxws.stub2html.service.Variable2Stub.convertToStub(Variable2Stub.java:35)
>         at org.jaxws.stub2html.service.WebMethodStubSetFactory.addRequestStubs(WebMethodStubSetFactory.java:39)
>         at org.jaxws.stub2html.service.WebMethodStubSetFactory.createWebMethodStubSet(WebMethodStubSetFactory.java:23)
>         at org.jaxws.stub2html.service.WebServiceStubSetFactory.createWebServiceStubSet(WebServiceStubSetFactory.java:25)
>         at org.jaxws.wsdl2html.service.Wsdl2Html.generateHtml(Wsdl2Html.java:28)
>         at org.jaxws.wsdl2html.ui.Wsdl2HtmlMain.main(Wsdl2HtmlMain.java:48)
> 
> D:\Downloads\wsdl2html-2.0.1-jarset\wsdl2html-2.0.1>
> 
> 
> 
> 

Cheers,
Eddy

**Comment by chenjianjx** [comment]
Can you send me your wsdl file or url?  If it has to be private, please send it to chenjianjx@gmail.com

**Comment by chenjianjx** [comment]
Please try version 2.0.2
