### ISSUE TITLE
Won't work with ebay.wsdl

### ISSUE THREAD

**Issue by Anzulo** [chenjianjx/wsdl2html#8]
I've tried using the tool (v3.0.2) with the offical ebay wsdl without success.

http://developer.ebay.com/webservices/latest/ebaySvc.wsdl

![image](https://cloud.githubusercontent.com/assets/2446115/18441399/36ea42ba-790d-11e6-8477-e867c56e752a.png)

**Comment by chenjianjx** [comment]
this project relies on wsimport.  Some wsdls don't work with wsimport.  And if that happens, there is nothing that wsdl2html can do.  Sorry about that.
